import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Montserrat({
  subsets: ["latin"],
});

const geistMono = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Todo Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.className} ${geistMono.className} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
